### ISSUE TITLE
Get rid of the warnings when starting the app

### ISSUE THREAD

**Issue by lipis** [excalidraw/excalidraw-desktop#82]
<img width="803" alt="Screenshot 2020-03-30 at 7 27 14 PM" src="https://user-images.githubusercontent.com/125676/77937116-8b04ff00-72bc-11ea-865a-b5e9110cca63.png">

**Comment by shrirambalaji** [comment]
@lipis I'd like to take this up. 

**CSP Errors**

We need to add a Content-Security-Policy meta tag to the [public/index.html](https://github.com/excalidraw/excalidraw/blob/master/public/index.html) file based on Electron's security recommendation [doc](https://github.com/electron/electron/blob/master/docs/tutorial/security.md#6-define-a-content-security-policy) about CSP. Something like this should work:

```html
<meta
  http-equiv="Content-Security-Policy"
  content="block-all-mixed-content; child-src 'none'; connect-src http: ws:; default-src 'none'; font-src 'self' data: https:; form-action 'none'; frame-src 'none'; img-src 'self' data: ; manifest-src 'none'; media-src 'none'; object-src 'none'; script-src 'self' 'unsafe-inline' https://www.googletagmanager.com https://www.google-analytics.com; style-src 'self' 'unsafe-inline' https:; worker-src 'none';"
/>;

```

Also we seem to be using an external image resource hosted on AWS [here]( https://github.com/excalidraw/excalidraw/blob/master/src/styles.scss#L351). If we can switch that out by hosting that image ourselves, then we don't need to modify the csp for `img-src` and load only data uris or images hosted on excalidraw.com. If we do use an image cdn that I'm unaware of, then we'd have to add that as well to the csp.

Let me know if this looks alright to you.

**Comment by lipis** [comment]
Sure.. go for it

**Comment by shrirambalaji** [comment]
@lipis The `crossorigin=anonymous` on the [font preload links](https://github.com/excalidraw/excalidraw/blob/b971737d326ff2e2558b899fd04ba55676388b5e/public/index.html#L68) are the reason for the following errors. But, if we remove the attribute, excalidraw web will throw warnings saying the `preload` cannot be used. This is probably because the fonts are loaded from the local filesystem in case of electron.

![image](https://user-images.githubusercontent.com/11358903/79041016-2033bc00-7c0a-11ea-9ee8-f645b1084612.png)

Also, I'm not entirely sure how the .asar file is made, but we could add in a way to remove the `crossOrigin` attribute for the font preload links.
